### ISSUE TITLE
rostopic echo is stumbling

### ISSUE THREAD

**Issue by stonier** [stonier/win_ros#35]
```
[WARN] [WallTime: 1336487500.975000] Inbound TCP/IP connection failed: 'NoneType' object is not iterable
data: hello world 840

---
data: hello world 841

---
data: hello world 842
```

**Comment by stonier** [comment]
Also happening with rostopic pub.

**Comment by stonier** [comment]
Source is in rospy/src/rospy/impl/tcpros_base.py

**Comment by stonier** [comment]
Traceback information:

```
Traceback (most recent call last):
  File "build\bdist.win32\egg\rospy\impl\tcpros_base.py", line 316, in _tcp_server_callback
    err_msg = self.topic_connection_handler(sock, client_addr, header)
  File "build\bdist.win32\egg\rospy\impl\tcpros_pubsub.py", line 349, in topic_connection_handler
    topic.add_connection(transport)
  File "build\bdist.win32\egg\rospy\topics.py", line 900, in add_connection
    super(_PublisherImpl, self).add_connection(c)
  File "build\bdist.win32\egg\rospy\topics.py", line 387, in add_connection
    for fd in self.connection_poll.error_iter():
TypeError: 'NoneType' object is not iterable
```

**Comment by stonier** [comment]
Could be related to this - it is calling the error_iter  function of Poller in rospy/topics.py:204 which has no implementation for windows.

**Comment by stonier** [comment]
Patching bugfix : https://code.ros.org/trac/ros/ticket/3959

It's not a real solution though, just a no-op solution. Real solution issue opened at #36.
