### ISSUE TITLE
Ungraceful exit for rostopic echo

### ISSUE THREAD

**Issue by stonier** [stonier/win_ros#59]
When doing ctrl-c on a rostopic echo, you can see the following

<pre>
Traceback (most recent call last):
  File "C:\work\build\bin\rostopic", line 2, in <module>
    execfile("C:/work/src/ros_comm/tools/rostopic/scripts/rostopic")
  File "C:/work/src/ros_comm/tools/rostopic/scripts/rostopic", line 35, in <module>
    rostopic.rostopicmain()
  File "C:/work/src/ros_comm/tools/rostopic/src\rostopic\__init__.py", line 1637, in
rostopicmain
    _rostopic_cmd_echo(argv)
  File "C:/work/src/ros_comm/tools/rostopic/src\rostopic\__init__.py", line 997, in _
rostopic_cmd_echo
    _rostopic_echo(topic, callback_echo, bag_file=options.bag)
  File "C:/work/src/ros_comm/tools/rostopic/src\rostopic\__init__.py", line 687, in _
rostopic_echo
    time.sleep(0.1)
IOError: [Errno 4] Interrupted function call
</pre>

**Comment by stonier** [comment]
Probably just needs an exception catch for IOError around the sleep call.

**Comment by stonier** [comment]
Same issue as for rospy - https://code.ros.org/trac/ros/ticket/3421
